steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # Tests
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]
    
  # Build
  - name: node:12.16.1
    entrypoint: "npm"
    args: ["run", "prerender"]

  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
