steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: 'npm'
    args: ["install"]
  # Tests
  # - name: "gcr.io/cloud-builders/npm"
  #   entrypoint: 'npm'
  #   args: ["run", "test"]
  # Build
  - name: node:12.16.1
    entrypoint: "npm"
    args: ["run", "build:ssr"]
  # Testing list
  - name: 'ubuntu'
    args: ['ls -la', 'pwd']
  # install functions package.json 
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    entrypoint: 'npm'
    args: ['install']
  # Copy
  - name: "gcr.io/cloud-builders/npm"
    dir: 'functions'
    entrypoint: 'npm'
    args: ["run", "copy"]
  # Testing list
    - name: 'ubuntu'
    args: ['ls -la', 'pwd']
  # Deploy functions & hosting 
  - name: "gcr.io/nuestrodinero/firebase"
    dir: 'functions'
    args: ["deploy","--project=nuestrodinero","--only=hosting,functions"]