steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: 'npm'
    args: ["install"]
  - name: node:12.16.1
    entrypoint: "npm"
    args: ["run", "build:ssr"]
  - name: "gcr.io/nuestrodinero/firebase"
    entrypoint: 'firebase'
    args: ["deploy","--project=nuestrodinero","--only=hosting,functions"]