"use strict";
exports.__esModule = true;
exports.PODER_ADJUDICADOR = 'Poder adjudicador';
exports.PODER_TIPO = 'Tipo de poder adjudicador y principal actividad ejercida';
exports.TIPO = 'Tipo';
exports.ACTIVIDAD = 'Actividad principal ejercida';
exports.NOMBRE = 'Nombre';
exports.NIF = 'Número de identificación fiscal';
exports.DIRECCION = 'Dirección';
exports.LOCALIDAD = 'Localidad';
exports.PROVINCIA = 'Provincia';
exports.CP = 'Código postal';
exports.PAIS = 'País';
exports.TELEFONO = 'Teléfono';
exports.EMAIL = 'Correo electrónico';
exports.WEB = 'Dirección principal';
exports.OFERTAS_RECIBIDAS = 'Ofertas recibidas';
exports.NUM_OFERTAS_RECIBIDAS = 'Número de ofertas recibidas';
exports.ADJUDICATARIOS = 'Adjudicatarios';
exports.VALOR_OFERTAS = 'Valor de las ofertas';
exports.FECHA_ANUNCIO = 'Fecha de envío del anuncio';
exports.DESCRIPCION_LICITACION = 'Descripción de la licitación';
exports.CODIGO_CPV = 'Códigos CPV';
exports.FORMALIZACION_CONTRATOS = 'Anuncio de formalización de contratos';
// REGEXP
exports.enumeracionDeListasRegexp = /([\d\.]+(?=\))|[:\)])/g;
exports.dotsCharsAndSpacesRegexp = /[[\.a-z\s]+/g;
